"""
A capture simulator that is independent of the model's own image formation, for testing without the "inverse crime"
(evaluating an inversion on data generated by its own forward model).

What differs from optics/camera.py (which training and reconstruction use):
  * PSF: the 2D pupil is propagated with a matrix Fourier transform (Soummer et al., Opt. Express 2007) and textbook
    paraxial defocus, instead of the 1D Hankel transform + cubic-spline resampling.
  * Spectrum: several wavelengths per color channel instead of one.
  * Discretization: many more depth layers, and the scene / PSF live on a grid finer than the sensor pixels and are
    binned down to them.
  * Sensor: Poisson shot noise + Gaussian read noise in electrons and ADC quantization, output as a raw Bayer mosaic.

Shared on purpose: the DOE design (heightmap1d), material dispersion, the diffraction-efficiency mix, and the layered
occlusion compositing (BaseCamera._capture_impl).
"""
import math

import numpy as np
import torch
import torch.nn.functional as F

from util.fft import fftshift
from util.helper import depthmap_to_layereddepth, heightmap_to_phase, refractive_index

# Three samples across each color filter's band (a box approximation of the Bayer filter responses), in meters.
BAND_WAVELENGTHS = [
    [605e-9, 632e-9, 660e-9],  # R
    [520e-9, 550e-9, 580e-9],  # G
    [430e-9, 460e-9, 490e-9],  # B
]


def pupil_heightmap(camera, height_scale=1.0):
    """DOE height on the 2D mask grid (looked up by radius from the 1D design) and the circular aperture mask."""
    n = camera.mask_size
    pitch = camera.mask_pitch
    x = (torch.arange(n, dtype=torch.float64) - n / 2 + 0.5) * pitch
    r = torch.sqrt(x[:, None] ** 2 + x[None, :] ** 2)
    # heightmap1d()[k] is the height of the ring (k * pitch, (k + 1) * pitch] (see BaseRotationallySymmetricCamera)
    height1d = camera.heightmap1d().detach().double().cpu()
    ind = (torch.ceil(r / pitch) - 1).long().clamp(0, height1d.numel() - 1)
    aperture = (r <= camera.mask_diameter / 2).double()
    return height_scale * height1d[ind] * aperture, aperture, x


@torch.no_grad()
def psf_mft(height2d, aperture, x, wavelength, depth, focal_depth, sensor_distance, out_size, out_pitch,
            modulate_phase=True):
    """Intensity PSF on an out_size^2 grid (pitch out_pitch, center at index out_size // 2), sum-normalized.

    Pupil field: aperture * exp(i * (DOE phase + paraxial defocus)), propagated to the sensor by Fraunhofer
    diffraction, evaluated directly at the output samples with a matrix Fourier transform.
    """
    device = height2d.device
    r2 = x[:, None] ** 2 + x[None, :] ** 2
    phase = math.pi * r2 / wavelength * (1. / depth - 1. / focal_depth)
    if modulate_phase:
        phase = phase + heightmap_to_phase(height2d, wavelength, refractive_index(wavelength))
    field = (aperture * torch.exp(1j * phase)).to(torch.complex64)

    u = (torch.arange(out_size, dtype=torch.float64, device=device) - out_size // 2) * out_pitch
    A = torch.exp(-2j * math.pi * u[:, None] * x[None, :] / (wavelength * sensor_distance)).to(torch.complex64)
    psf = (A @ field @ A.T).abs() ** 2
    return psf / psf.sum()


@torch.no_grad()
def psf_stack(camera, depths, out_size, out_pitch, wavelengths=BAND_WAVELENGTHS, height_scale=1.0,
              focus_offset=0.0, diffraction_efficiency=None, device='cuda'):
    """PSFs for each color channel and depth: 3 x len(depths) x out_size x out_size, each sum-normalized.

    Each channel averages its wavelengths. As in MixedCamera, the DOE-modulated and the unmodulated PSFs are mixed by
    the diffraction efficiency. height_scale and focus_offset [m] model fabrication / assembly errors.
    """
    if diffraction_efficiency is None:
        diffraction_efficiency = camera.diffraction_efficiency
    focal_depth = camera.focal_depth + focus_offset
    sensor_distance = 1. / (1. / camera.focal_length - 1. / focal_depth)
    height2d, aperture, x = (t.to(device) for t in pupil_heightmap(camera, height_scale))

    psf = torch.zeros(3, len(depths), out_size, out_size, device=device)
    for c, channel_wavelengths in enumerate(wavelengths):
        for d, depth in enumerate(depths):
            for wl in channel_wavelengths:
                args = (height2d, aperture, x, wl, float(depth), focal_depth, sensor_distance, out_size, out_pitch)
                psf[c, d] += (diffraction_efficiency * psf_mft(*args, modulate_phase=True) +
                              (1 - diffraction_efficiency) * psf_mft(*args, modulate_phase=False)).float()
            psf[c, d] /= len(channel_wavelengths)
    return psf


@torch.no_grad()
def render_layered(camera, img_linear, depth_ips, psf, tile=1024, device='cuda'):
    """Occlusion-aware layered rendering, tiled.

    img_linear: 1 x 3 x H x W, depth_ips: 1 x 1 x H x W in [0, 1] (inverse-perspective depth), psf: 3 x L x n x n
    centered PSFs (center at n // 2), one per depth layer; layer k covers depth_ips in (k / L, (k + 1) / L].
    Returns the 1 x 3 x H x W blurred linear image.
    """
    n_layers, n = psf.shape[1], psf.shape[-1]
    halo = n // 2
    h, w = img_linear.shape[-2:]
    n_ty, n_tx = -(-h // tile), -(-w // tile)
    # Reflect by the halo; the rest of the last tile only produces output that is cropped away.
    fill = (0, n_tx * tile - w, 0, n_ty * tile - h)
    img_p = F.pad(F.pad(img_linear, (halo,) * 4, mode='reflect'), fill)
    depth_p = F.pad(F.pad(depth_ips, (halo,) * 4, mode='reflect'), fill)

    size = tile + 2 * halo
    p = (size - n) // 2
    psf = fftshift(F.pad(psf, (p, size - n - p, p, size - n - p)), dims=(-1, -2)).unsqueeze(0).to(device)

    out = torch.zeros(1, 3, n_ty * tile, n_tx * tile)
    for ty in range(n_ty):
        for tx in range(n_tx):
            y0, x0 = ty * tile, tx * tile
            sl = (..., slice(y0, y0 + size), slice(x0, x0 + size))
            layered = depthmap_to_layereddepth(depth_p[sl].to(device), n_layers, binary=True)
            volume = layered * img_p[sl].to(device)[:, :, None]
            captimg, _ = camera._capture_impl(volume, layered, psf, occlusion=True)
            out[..., y0:y0 + tile, x0:x0 + tile] = captimg[..., halo:halo + tile, halo:halo + tile].cpu()
    return out[..., :h, :w]


def mosaic_rggb(img):
    """1 x 3 x H x W -> H x W Bayer mosaic, same layout as util.helper.to_bayer (R at (0, 0), B at (1, 1))."""
    img = img[0]
    raw = img[1].clone()
    raw[0::2, 0::2] = img[0, 0::2, 0::2]
    raw[1::2, 1::2] = img[2, 1::2, 1::2]
    return raw


def sensor_raw(irradiance, full_well=10000., read_noise=3., bit_depth=12, exposure_percentile=99.5,
               exposure_level=0.9):
    """Sensor-resolution linear RGB irradiance (1 x 3 x H x W) -> noisy, quantized raw mosaic (H x W, uint16).

    Exposure puts the given percentile at exposure_level of full well; then Poisson shot noise and Gaussian read noise
    (in electrons), and quantization to bit_depth bits. White level is 2 ** bit_depth - 1, black level 0.
    """
    raw = mosaic_rggb(irradiance)
    scale = exposure_level * full_well / np.percentile(raw.numpy(), exposure_percentile)
    electrons = torch.poisson((raw * scale).clamp(min=0))
    electrons = electrons + read_noise * torch.randn_like(electrons)
    white = 2 ** bit_depth - 1
    return torch.round(electrons / full_well * white).clamp(0, white).numpy().astype(np.uint16)
